"""
report_generator.py
───────────────────
Generates a styled PDF inspection report using fpdf2.

Report sections
───────────────
1. Title + timestamp
2. Original image
3. Annotated image (with bounding boxes)
4. Defect detection table
5. LLaVA AI analysis
6. Overall verdict  (PASS / WARNING / FAIL)
"""

import os
import io
import tempfile
from datetime import datetime
from typing import List, Dict, Optional

import numpy as np
from PIL import Image
from fpdf import FPDF


# ── VERDICT LOGIC ────────────────────────────────────────
def get_verdict(report: List[Dict]) -> str:
    """Return 'FAIL', 'WARNING', or 'PASS' based on severity counts."""
    if any(d["severity"] == "HIGH" for d in report):
        return "FAIL"
    if any(d["severity"] == "MEDIUM" for d in report):
        return "WARNING"
    return "PASS"


# ── PDF CLASS ────────────────────────────────────────────
class InspectionReport(FPDF):
    """Custom FPDF subclass with a branded header and footer."""

    def header(self):
        self.set_font("Helvetica", "B", 12)
        self.set_fill_color(30, 30, 50)
        self.set_text_color(255, 255, 255)
        self.cell(0, 12, "  Visual Inspection Agent — Manufactured-Defect Report",
                  align="L", fill=True, new_x="LMARGIN", new_y="NEXT")
        self.set_text_color(0, 0, 0)
        self.ln(3)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f"Page {self.page_no()} — Generated by Visual Inspection Agent",
                  align="C")


# ── HELPER: save ndarray to temp PNG ─────────────────────
def _ndarray_to_tmp_png(img_rgb: np.ndarray) -> str:
    """Save an RGB ndarray to a temp PNG file and return the path."""
    tmp = tempfile.NamedTemporaryFile(delete=False, suffix=".png")
    Image.fromarray(img_rgb).save(tmp.name)
    tmp.close()
    return tmp.name


# ── MAIN FUNCTION ────────────────────────────────────────
def generate_pdf_report(
    original_img_path: str,
    annotated_img_rgb: Optional[np.ndarray],
    report: List[Dict],
    llava_analysis: str,
    output_path: str = "inspection_report.pdf",
) -> str:
    """
    Build the PDF and save it to *output_path*.

    Parameters
    ----------
    original_img_path  : str         Path to the original uploaded image.
    annotated_img_rgb  : np.ndarray  Annotated image (RGB).  May be None.
    report             : list[dict]  Detections from defect_detector.
    llava_analysis     : str         LLaVA natural-language text.
    output_path        : str         Destination PDF path.

    Returns
    -------
    str  — absolute path to the saved PDF.
    """
    pdf = InspectionReport(orientation="P", unit="mm", format="A4")
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # ── 1. Title block ─────────────────────────────────
    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(30, 30, 50)
    pdf.cell(0, 10, "Inspection Report", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(100, 100, 100)
    ts = datetime.now().strftime("%Y-%m-%d  %H:%M:%S")
    pdf.cell(0, 7, f"Timestamp: {ts}", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(6)

    # ── 2. Verdict badge ───────────────────────────────
    verdict = get_verdict(report)
    colors  = {"PASS": (0, 168, 107), "WARNING": (255, 140, 0), "FAIL": (200, 30, 30)}
    r, g, b = colors[verdict]
    pdf.set_fill_color(r, g, b)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 12, f"Overall Verdict:  {verdict}", align="C", fill=True,
             new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(0, 0, 0)
    pdf.ln(8)

    # ── 3. Images (side by side if both available) ─────
    page_w = pdf.w - pdf.l_margin - pdf.r_margin
    img_w  = (page_w - 6) / 2  # 6 mm gap

    tmp_files = []

    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(img_w, 7, "Original Image", align="C")
    pdf.cell(6)
    pdf.cell(img_w, 7, "Annotated Image", align="C", new_x="LMARGIN", new_y="NEXT")

    img_h = 70  # mm
    x_left  = pdf.l_margin
    x_right = pdf.l_margin + img_w + 6
    y_img   = pdf.get_y()

    if os.path.exists(original_img_path):
        pdf.image(original_img_path, x=x_left, y=y_img, w=img_w, h=img_h)

    if annotated_img_rgb is not None:
        tmp_ann = _ndarray_to_tmp_png(annotated_img_rgb)
        tmp_files.append(tmp_ann)
        pdf.image(tmp_ann, x=x_right, y=y_img, w=img_w, h=img_h)

    pdf.set_y(y_img + img_h + 6)

    # ── 4. Detection summary ───────────────────────────
    high   = sum(1 for d in report if d["severity"] == "HIGH")
    medium = sum(1 for d in report if d["severity"] == "MEDIUM")
    low    = sum(1 for d in report if d["severity"] == "LOW")

    pdf.set_font("Helvetica", "B", 12)
    pdf.set_fill_color(240, 240, 250)
    pdf.cell(0, 8, "Detection Summary", fill=True, new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    pdf.ln(1)

    col_w = page_w / 3
    for label, val, clr in [
        ("🔴 HIGH",   high,   (200, 30,  30)),
        ("🟠 MEDIUM", medium, (255, 140,  0)),
        ("🟡 LOW",    low,    (180, 160,  0)),
    ]:
        pdf.set_text_color(*clr)
        pdf.set_font("Helvetica", "B", 11)
        pdf.cell(col_w, 8, f"{label}:  {val}", align="C")
    pdf.ln(10)
    pdf.set_text_color(0, 0, 0)

    # ── 5. Detection table ─────────────────────────────
    if report:
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_fill_color(30, 30, 50)
        pdf.set_text_color(255, 255, 255)
        heads = ["#", "Object", "Severity", "Confidence", "Location"]
        widths = [10, 35, 25, 28, page_w - 10 - 35 - 25 - 28]
        for h, w in zip(heads, widths):
            pdf.cell(w, 8, h, border=1, fill=True, align="C")
        pdf.ln()

        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(0, 0, 0)
        severity_rgb = {"HIGH": (255, 220, 220), "MEDIUM": (255, 235, 200), "LOW": (255, 255, 200)}

        for i, d in enumerate(report):
            fill_r, fill_g, fill_b = severity_rgb.get(d["severity"], (240, 240, 240))
            pdf.set_fill_color(fill_r, fill_g, fill_b)
            row = [str(i + 1), d["object"], d["severity"],
                   f"{d['confidence']:.2f}", d["location"]]
            for val, w in zip(row, widths):
                pdf.cell(w, 7, val, border=1, fill=True, align="C")
            pdf.ln()
    else:
        pdf.set_font("Helvetica", "I", 10)
        pdf.cell(0, 8, "No objects detected.", new_x="LMARGIN", new_y="NEXT")

    pdf.ln(6)

    # ── 6. LLaVA AI Analysis ───────────────────────────
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_fill_color(240, 240, 250)
    pdf.cell(0, 8, "AI Analysis (LLaVA)", fill=True, new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(40, 40, 40)

    # Safely handle non-ASCII characters from LLaVA
    safe_analysis = llava_analysis.encode("latin-1", errors="replace").decode("latin-1")
    pdf.multi_cell(0, 5, safe_analysis)

    # ── Save PDF ───────────────────────────────────────
    pdf.output(output_path)

    # Cleanup temp annotation image
    for p in tmp_files:
        try:
            os.unlink(p)
        except OSError:
            pass

    return os.path.abspath(output_path)
